### ISSUE TITLE
Upgrade luxai_s2 dependency to v2.1.9 to resolve InvalidRequirement error

### ISSUE THREAD

**Issue by dfcorbin** [RoboEden/jux#7]
When I run

```
import jux.env
```

I get the following error:

```
Traceback (most recent call last):
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3039, in _dep_map
    return self.__dep_map
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2835, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 209, in _parse_specifier
    tokenizer.consume("WS")
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 183, in enclosing_tokens
    self.raise_syntax_error(
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected closing RIGHT_PARENTHESIS
    opencv-python (>=3.) ; extra == 'all'
                  ~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/jux/env.py", line 7, in <module>
    from luxai_s2 import LuxAI_S2
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/luxai_s2/__init__.py", line 2, in <module>
    from .version import __version__
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/luxai_s2/version.py", line 3, in <module>
    __version__ = pkg_resources.require("luxai-s2")[0].version
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 956, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 820, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2755, in requires
    dm = self._dep_map
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3041, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3051, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3104, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/dfcorbin/miniconda3/envs/luxai_s2/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    opencv-python (>=3.) ; extra == 'all'
```

According to [this (closed) issue](https://github.com/Lux-AI-Challenge/Lux-Design-S2/issues/221) on the Lux-Design-S2 repository, the issue has been fixed for luxai_s2 v2.1.9 (which was true when I tested it on my system). However, it seems that the latest version of  jux still depends on luxai_s2 v2.1.0. Could this be updated so that the error may be resolved?

**Comment by liqimai** [comment]
fixed in v2.1.1
